version: '3.7'

services:

  mt:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --log-config logging.yml
    restart: unless-stopped
    runtime: nvidia  # Comment out in local
    ports:
      - "7872:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - .:/app
      - ../translation-models:/app/models
      - ./config.json:/app/config.json
    security_opt:
      - seccomp:unconfined
    environment:
      - MT_API_CONFIG=/app/config.json
      - MT_API_DEVICE=gpu
      - MT_API_THREADS=16
      - MODELS_ROOT=/app/models
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      